#ifndef TEST_CSV_SENSOR_H
#define TEST_CSV_SENSOR_H

void test_capteur_csv_init_valid_file_returns_count(void);
void test_capteur_csv_init_missing_file_returns_minus_one(void);
void test_capteur_csv_init_ignores_comments_and_blank_lines(void);
void test_capteur_csv_returns_value_for_valid_index(void);
void test_capteur_csv_returns_sentinel_for_out_of_bounds_index(void);
void test_capteur_csv_returns_sentinel_before_init(void);
void test_capteur_csv_init_clamps_out_of_range_values(void);
void test_capteur_csv_fermer_resets_state(void);
void test_capteur_csv_init_twice_without_fermer_does_not_overflow(void);

#endif // TEST_CSV_SENSOR_H
