name: Code static analysis

on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Just
        run: sudo snap install just --classic

      - name: Install CPPCheck
        run: sudo apt install cppcheck

      - name: Run static analysis
        run: just check
